services:
  - type: web
    name: smartprep
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
